#!/usr/bin/env python

from autobahn.twisted.websocket import WebSocketClientProtocol
from autobahn.twisted.websocket import WebSocketClientFactory
from autobahn.twisted.websocket import connectWS

from twisted.python import log
from twisted.internet import reactor
from twisted.internet.protocol import ReconnectingClientFactory
import sys
import os
import requests
import json


class MyClientProtocol(WebSocketClientProtocol):

    def onOpen(self):
        self.message_id = 0
        self.sendMessageToChannel("hello Jan", "G2S151RCP")

    def onMessage(self, payload, isBinary):
        print("Text message received: {0}".format(payload.decode('utf8')))
        res_string = payload.decode('utf8')
        res_json = json.loads(res_string)
        if 'reconnect_url' in res_json['type']:
            wssURL = res_json['url']

    def sendMessageToChannel(self, text, channel):
        self.message_id = self.message_id + 1
        message_type = "message"
        message_channel = channel
        message_text = text
        message = {
            "id": self.message_id,
            "type": message_type,
            "channel": message_channel,
            "text": message_text
        }
        self.sendMessage(json.dumps(message))


class ourWS_reconnecting(ReconnectingClientFactory, WebSocketClientFactory):
    def __init__(self, *args, **kwargs):
        WebSocketClientFactory.__init__(self, *args, **kwargs)

def main():
    apikey = os.environ['ROLLMOPS_SLACK_API_KEY']
    requestURL = "http://slack.com/api/rtm.start?token=%s" % apikey

    res = requests.get(requestURL)
    try:
        json_reqsponse = json.loads(res.text)
    except:
        print
        print "received broken json from %s" % requestURL
        sys.exit(1)

    wssURL = json_reqsponse["url"]

    log.startLogging(sys.stdout)
    print requestURL

    factory = ourWS_reconnecting(wssURL)
    factory.protocol = MyClientProtocol

    connectWS(factory)
    reactor.run()

if __name__ == '__main__':
    main()
